### ISSUE TITLE
建议加一个disabled或者readonly的option，控制所有节点不能勾选

### ISSUE THREAD

**Issue by hillwu126com** [cipchk/ng-tree-antd#1]

**Comment by cipchk** [comment]
sorry, the document is not summary.

the `nodes` is array  of the tree, and each node may contain the following fileds: 

+ `id` unique id
+ `name` default displayed filed, you can setting `displayField` of `options` property
+ `checked` specifies whether the checkbox is selected
+ `disableCheckbox` disable checkbox
+ `halfChecked` achieve a 'check all' effect
+ `children` an array of the node's children.
+ `hasChildren` for async data load, so you need setting `getChildren` of `options` property

I will improve documentation.
