### ISSUE TITLE
不支持多选吗？

### ISSUE THREAD

**Issue by fireswork** [cipchk/ng-tree-antd#13]
checkbox不存在的时候

**Comment by xbu** [comment]
angular2-tree支持的，shift多选。但nztree不知道怎么搞，代码没看完

**Comment by fireswork** [comment]
@xbu 看了哈angular-tree-component,需要自定义actionMapping才行，稍微加几句代码改动一下就可以了
`import { TREE_ACTIONS, KEYS, IActionMapping } from 'angular-tree-component';
const actionMapping: IActionMapping = {
  mouse: {
    click: TREE_ACTIONS.TOGGLE_SELECTED_MULTI
  }
}
....
_options: NzTreeOptions = {
    actionMapping,
    animateExpand: true
  };
`
建议作者加上去 @cipchk

**Comment by cipchk** [comment]
下个版本加上。
