### ISSUE TITLE
关于自定义图标

### ISSUE THREAD

**Issue by xbu** [cipchk/ng-tree-antd#14]
你好，我查了angular2-tree关于自定义图标，有人说用custom template可以，https://angular2-tree.readme.io/discuss/58945fe1f4de7c1b003265bb

我在nztree上试了下 不生效，看源代码发现nztree封装了ng-template，这是不是以为这我不能在nztree上使用ng-template了。

我的需求是在node上带一个属性，然后根据属性应用不同的font-icon来显示图标。

谢谢

**Comment by cipchk** [comment]
你可以使用 `nzTitle` 属性：

```html
<ng-template #nzTitle let-node>
{{node.displayField}}
</ng-template>
```

**Comment by xbu** [comment]
这么使用吗？页面没效果，我看源代码简洁，直接改代码了，但是重复引入代码，不好的做法
```
<ng-template nzTitle="<i class="anticon anticon-check-circle"></i>" let-node>
           {{node.displayField}}
</ng-template>
```

**Comment by apphost** [comment]
`            <nz-tree [nzNodes]="nodes" [nzShowLine]="true">
                <ng-template #nzTitle let-node>
                    {{node.displayField}}
                </ng-template>
            </nz-tree>
`


It's said:

> ERROR TypeError: Cannot read property 'displayField' of undefined

**Comment by cipchk** [comment]
`name` default displayed filed, you can setting `displayField` of `options` property

**Comment by bokire** [comment]
`<ng-template #nzTitle let-node>
{{node.displayField}}
</ng-template>`
在ng-alian中的页面试了下这样的写法,取不到node

**Comment by cipchk** [comment]
我会在晚上写一个示例放在DEMO站上中。

**Comment by alexspring123** [comment]
@cipchk  请问使用nzTitle的模板demo写好了吗？

**Comment by cipchk** [comment]
抱歉，迟来的爱，给忘记了。
