### ISSUE TITLE
ng-tree-antd 无法自适应主题色

### ISSUE THREAD

**Issue by xbu** [cipchk/ng-tree-antd#15]
引入ng-tree-antd 并使用checkbox属性的时候发现颜色还是蓝色，而不是系统目前选择的其他主题色。
https://cipchk.github.io/ng-alain/#/elements/tree-antd       验证过 也是一样，作者好像是在css里写死了

**Comment by cipchk** [comment]
谢谢提醒，关于主题色系这一部分是 ng-alain 的特性之一，我会在 ng-alain 修复它。
