### ISSUE TITLE
[bug]点击node时nzFocus事件被触发两次

### ISSUE THREAD

**Issue by alexspring123** [cipchk/ng-tree-antd#2]

**Comment by cipchk** [comment]
的确，这是因为 `angular-tree-compent` 的设计如此；当激活某个项时，会收到五个事件，包括：

PNG:
![tim 20171010140552](https://user-images.githubusercontent.com/2987467/31371564-28843518-adc4-11e7-82b2-96617358293d.png)

你可以在监听 `nzEvent` 观察到这一情况。

**Comment by alexspring123** [comment]
谢谢。 但是不太理解为什么这样设计？
