### ISSUE TITLE
初始化时不能勾选父节点状态

### ISSUE THREAD

**Issue by lyc152** [cipchk/ng-tree-antd#25]
```
this.nodes = [
      {
        name: '账户',
        hasChildren: true,
        checked: false,
        children: [
            {
              id: 1,
              name: 'name1',
              checked: false
            },
            {
              id: 2,
              name: 'name2',
              checked: true
            }
        ]
      }
    ]

```

期望的是
![image](https://user-images.githubusercontent.com/4793878/34758878-d570c934-f613-11e7-965c-7375f2fd5973.png)

现在页面展示是
![image](https://user-images.githubusercontent.com/4793878/34758849-b96ca00a-f613-11e7-9452-521f23f829cd.png)

请问有好的解决方案吗

**Comment by zhuanjiao** [comment]
当前只能自动勾选上一级，超过两级就不能自动勾选了
