### ISSUE TITLE
请教下如何打包成第三方lib的

### ISSUE THREAD

**Issue by dyh333** [cipchk/ng-tree-antd#28]
如题，能否简要说明下步骤和工具 谢谢。

**Comment by cipchk** [comment]
所有命令都在 `package.json` 当中：

```bash
# 发布
npm run release
# 发布DEMO至github
npm run demo.gh-pages
```

OVER.

**Comment by dyh333** [comment]
![image](https://user-images.githubusercontent.com/1221313/35387337-439a6378-020a-11e8-8c1f-63a20d69f029.png)
npm-run-all 是什么命令 能否指教下
@cipchk

**Comment by cipchk** [comment]
https://www.npmjs.com/search?q=npm-run-all

**Comment by dyh333** [comment]
@cipchk , 不好意思，还得再请教一下，安装完npm-run-all后运行 release 还是报错。网上找了一圈没找到原因。
![image](https://user-images.githubusercontent.com/1221313/35424305-a619faee-028d-11e8-980b-12632d643ca7.png)

**Comment by cipchk** [comment]
我想应该是 `gulp-rollup` 升级了吧，你可以去看一下它的变更记录，当然 `ng-tree-antd` 应该也有同样问题，只不过我本地应该是用老的版本。
