### ISSUE TITLE
您好，请问这个怎么解决？

### ISSUE THREAD

**Issue by shuweitao** [cipchk/ng-tree-antd#36]
TreeNodeComponent.html:2 ERROR Error: [mobx] Autorun expects a function as first argument
![image](https://user-images.githubusercontent.com/14088111/37327313-c4f7f51c-26d0-11e8-9c63-65bca09f3427.png)

**Comment by cipchk** [comment]
https://github.com/500tech/angular-tree-component/issues/564

**Comment by shuweitao** [comment]
树不会自动靠右边展开!
![image](https://user-images.githubusercontent.com/14088111/37328747-424c0f1c-26d6-11e8-8191-e9875b631d24.png)
