### ISSUE TITLE
angular-tree-component should be placed into dependencies of package.json?

### ISSUE THREAD

**Issue by kinglionsoft** [cipchk/ng-tree-antd#42]
angular-tree-component should be placed into dependencies of package.json?

**Comment by cipchk** [comment]
`ng-tree-antd` always includes `peerDependencies`, if not found you can trying install to fixed this.

> BTW: ng-zorro-antd already included `nz-tree` in `0.7.x`

**Comment by kinglionsoft** [comment]
Nice work.  Thanks.
