### ISSUE TITLE
Top level remains intermedian status when execute specify operation

### ISSUE THREAD

**Issue by ryancui-** [cipchk/ng-tree-antd#6]
There are 3 levels menu. Do the operations:

- Check the third level (the path is intermedian, the item is checked)
- Check the top level (all items are checked)
- Uncheck the top level

expect all items are unchecked but the top remains intermedian.

I found everything OK in `angular-tree-component` demo page.

A gif explains the operations:
![ng-tree-antd_bug](https://user-images.githubusercontent.com/3788103/31927496-fee82728-b859-11e7-86ec-ac3826700963.gif)

**Comment by cipchk** [comment]
please check it.
