### ISSUE TITLE
父子节点关联关系开关

### ISSUE THREAD

**Issue by yunClouds** [cipchk/ng-tree-antd#8]
@cipchk  你好
能否支持设置：选中所有字节点时不自动关联选中父节点，只有用户主动选中才选中。

**Comment by cipchk** [comment]
你可以在 `angular-tree-component` 里的 [changeFilter](https://angular2-tree.readme.io/docs/events#changeFilter) 试试，我不确定能不能做到这一点；抑或至 [issues](https://github.com/500tech/angular-tree-component/issues) 看是否已经存在跟你相同需求的人。

**Comment by yunClouds** [comment]
好的谢谢

**Comment by ZhaoRd** [comment]
@yunClouds  你可以监听事件 `onCheck` ,在这里处理逻辑，
```
if($event.checked){
            this.selectNodeAndAllParents($event.node);
        }
        else{
            // 如果是子未选中，不影响父节点的状态
            this.deSelectNodeAndAllParents($event.node);
        }
```

```

deSelectNodeAndAllParents(node) {
        let parent = node.parent;
        if (parent) {
            // 保证父节点不受子节点取消而取消
            parent.data.checked=true;
            parent.data.halfChecked=false;
            this.deSelectNodeAndAllParents(parent);
        }
    }

```

效果如图
![image](https://user-images.githubusercontent.com/3433353/36080481-cea07c40-0fcb-11e8-95c4-b0d448918947.png)
