### ISSUE TITLE
angular5 --prod

### ISSUE THREAD

**Issue by adongroom** [cipchk/ng-tree-antd#9]
ERROR in Error at /Users/hanzhendong/workspace/web/angular-webapp/pclearner/node_modules/ng-tree-antd/components/nz-tree.component.d.ts.NzTreeComponent.html(59,13):  ("
          <ng-container
            [ngTemplateOutlet]="nzTitle"
            [ERROR ->][ngOutletContext]="{ $implicit: node, node: node, index: index }">
          </ng-container>
        ")

angular5    ng build --prod

**Comment by cipchk** [comment]
支持 Angular5 的代码暂时未发布，待 ng-zorro-antd 正式支持 v5 时吧。
